name: Release Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
  #   branches:
  #     - master
  #     - next
  # pull_request:
  #   branches:
  #     - '**'
  workflow_run:
    workflows: ['Test Workflow']
    types:
      - completed
    branches:
      - master
      - next
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: 'Release NPM'
    env:
      GITHUB_TOKEN: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GIT_USER: ${{ secrets.GIT_USER }}
      GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
    steps:
      - uses: actions/setup-node@v2.5.0
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-node-
      - name: Install Deps
        run: npm ci --ignore-scripts
      - name: Auth NPM
        run: echo "//registry.npmjs.org/:_authToken=${{ env.NPM_TOKEN }}" > ~/.npmrc
      - name: Auth Git
        run: |
          git config user.email "${{ env.GIT_EMAIL }}"
          git config user.name "${{ env.GIT_USER }}"
      - name: Build Libs
        run: npm run build:all
      - name: Pack Libs
        run: npm run pack
      - name: Release Latest
        if: ${{ github.ref == 'refs/heads/master' }}
        run: npm run release
      - name: Release Next
        if: ${{ github.ref == 'refs/heads/next' }}
        run: RELEASE_TAG=next npm run release:tag
