name: Release Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
  #   branches:
  #     - master
  #     - next
  # pull_request:
  #   branches:
  #     - '**'
  workflow_run:
    workflows: ['Test Workflow']
    types:
      - completed
    branches:
      - master
      - next
      - 'release/*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: 'Release NPM'
    env:
      GITHUB_TOKEN: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GIT_USER: ${{ secrets.GIT_USER }}
      GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
    steps:
      - uses: actions/setup-node@v2
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ env.GITHUB_TOKEN }}
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-node-
      - name: Auth NPM
        run: echo "//registry.npmjs.org/:_authToken=${{ env.NPM_TOKEN }}" > ~/.npmrc
      - name: Auth Git
        run: |
          git config user.email "${{ env.GIT_EMAIL }}"
          git config user.name "${{ env.GIT_USER }}"
      - name: Install Deps
        run: npm ci --ignore-scripts
      - run: npx nx-cloud start-ci-run
      - name: Build Libs
        run: npm run build:all
      - name: Pack Libs
        run: npm run pack
      - name: Release Latest
        if: ${{ github.ref == 'refs/heads/master' }}
        run: npm run release
      - name: Release Next
        if: ${{ github.ref == 'refs/heads/next' }}
        run: RELEASE_TAG=next npm run release:tag
      - name: Release Branch
        if: ${{ startsWith(github.ref, 'refs/heads/release/') }}
        run: RELEASE_BRANCH=\"${{ github.ref }}\" npm run release:branch
      - run: npx nx-cloud stop-all-agents
  agents:
    runs-on: ubuntu-latest
    name: Agents
    timeout-minutes: 60
    strategy:
      matrix:
        agent: [1, 2, 3]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install
      - name: Start Nx Agent ${{ matrix.agent }}
        run: npx nx-cloud start-agent
