name: Release Workflow

on:
  # Triggers the workflow after the Test Workflow has completed
  workflow_run:
    workflows: ['Test Workflow']
    types:
      - completed
    branches:
      - master
      - next
      - 'release/*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: false
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: 'Release NPM'
    env:
      RELEASE_BRANCH: ${{ github.event.workflow_run.head_branch }}
    steps:
      - uses: actions/setup-node@v2
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ env.RELEASE_BRANCH }}
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-node-
      - name: Auth NPM
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: Auth Git
        run: |
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git config --global user.name 'GitHub Actions Bot'
      - name: Install Deps
        run: npm ci --ignore-scripts
      - name: Release Latest
        if: ${{ env.RELEASE_BRANCH == 'master' }}
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Release Next
        if: ${{ env.RELEASE_BRANCH == 'next' }}
        run: RELEASE_TAG=next npm run release:tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Release Branch
        if: ${{ startsWith(env.RELEASE_BRANCH, 'release/') }}
        run: RELEASE_BRANCH=\"${{ env.RELEASE_BRANCH }}\" npm run release:branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Release Error Log
        if: failure()
        run: cat lerna-debug.log
      - name: Post Auth NPM
        if: always()
        run: rm ~/.npmrc
