name: Test Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - '**'
  # pull_request:
  #   branches:
  #     - '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stage: [Build, Test, Lint]
        include:
          - stage: Build
            cmd: 'npm run affected:build -- --parallel --base=${{ steps.test.outputs.BASE }}'
          - stage: Test
            cmd: 'npm run affected:test -- --parallel --base=${{ steps.test.outputs.BASE }}'
          - stage: Lint
            cmd: 'npm run affected:lint -- --parallel --base=${{ steps.test.outputs.BASE }}'
    steps:
      - uses: actions/setup-node@v2.5.0
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-node-
      - name: Install Deps
        run: npm ci --ignore-scripts
      - name: Get Latest Tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        id: previoustag
      - name: Set base ref as last tag
        run: echo '::set-output name=BASE::${{ steps.previoustag.outputs.tag }}'
        if: ${{ github.ref == 'refs/heads/master' }}
      - name: Set base ref as master
        run: echo '::set-output name=BASE::origin/master'
        if: ${{ github.ref != 'refs/heads/master' }}
      - name: ${{ matrix.stage }}
        run: ${{ matrix.cmd }}
